Repository knative-extensions/net-gateway-api, pull requests merged in 2021-12, with the labels that each got.

#213 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/XS, lgtm, approved

#214 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/XS, lgtm, approved

#211 Add docs about tested Gateway API/Ingress versions and unavailable features
  DEVELOPMENT.md
  README.md
  config/100-gateway-api.yaml
  docs/.test-version.template
  docs/test-version.md
  hack/release.sh
  hack/test-env.sh
  hack/update-codegen.sh
  test/e2e-common.sh
  test/e2e-tests.sh
  test/kind-conformance-contour.sh
  test/kind-conformance-istio.sh
  test/kind-e2e-contour.sh
  test/kind-e2e-istio.sh
  third_party/download-istio.sh
  third_party/istio/istio-ci-no-mesh.yaml
  third_party/istio/istio-kind-no-mesh.yaml
Labels: cla: yes, lgtm, size/L, approved

#216 Bump istio and Contour to the 1.11.5 and 1.19.1
  docs/test-version.md
  hack/test-env.sh
Labels: cla: yes, size/XS, lgtm, approved

#215 Generate Gateway API CRD only when kubectl exists
  hack/update-codegen.sh
Labels: cla: yes, size/XS, lgtm, approved

#219 Drop explicit indirect dependencies
  go.mod
  go.sum
  vendor/github.com/go-openapi/jsonpointer/.travis.yml
  vendor/github.com/go-openapi/jsonpointer/pointer.go
  vendor/github.com/go-openapi/jsonreference/.golangci.yml
  vendor/github.com/go-openapi/jsonreference/.travis.yml
  vendor/github.com/go-openapi/jsonreference/README.md
  vendor/github.com/go-openapi/jsonreference/go.mod
  vendor/github.com/go-openapi/jsonreference/go.sum
  vendor/github.com/go-openapi/spec/contact_info.go
  vendor/github.com/go-openapi/spec/license.go
  vendor/github.com/go-openapi/swag/.golangci.yml
  vendor/github.com/go-openapi/swag/.travis.yml
  vendor/github.com/go-openapi/swag/README.md
  vendor/github.com/go-openapi/swag/convert.go
  vendor/github.com/go-openapi/swag/convert_types.go
  vendor/github.com/go-openapi/swag/go.mod
  vendor/github.com/go-openapi/swag/go.sum
  vendor/github.com/go-openapi/swag/json.go
  vendor/github.com/go-openapi/swag/loading.go
  vendor/github.com/go-openapi/swag/util.go
  vendor/github.com/josharian/intern/README.md
  vendor/github.com/josharian/intern/go.mod
  vendor/github.com/josharian/intern/intern.go
  vendor/github.com/josharian/intern/license.md
  vendor/github.com/mailru/easyjson/buffer/pool.go
  vendor/github.com/mailru/easyjson/jlexer/lexer.go
  vendor/github.com/mailru/easyjson/jwriter/writer.go
  vendor/modules.txt
Labels: lgtm, size/XXL, approved

#220 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/rs/dnscache/.travis.yml
  vendor/github.com/rs/dnscache/LICENSE
  vendor/github.com/rs/dnscache/README.md
  vendor/github.com/rs/dnscache/dnscache.go
  vendor/github.com/rs/dnscache/go.mod
  vendor/github.com/rs/dnscache/go.sum
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/knative.dev/networking/test/test_images/httpproxy/httpproxy.go
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#221 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#222 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#223 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#225 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, lgtm, approved

#227 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#226 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/time/rate/rate.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/modules.txt
Labels: lgtm, size/M, approved
