Repository knative-extensions/net-gateway-api, pull requests merged in 2021-05, with the labels that each got.

#48 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
Labels: approved, cla: yes, lgtm, size/S

#49 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#51 Update DEVELOPMENT.md
  .github/workflows/kind-e2e.yaml
  DEVELOPMENT.md
  README.md
Labels: cla: yes, lgtm, size/M

#52 [Automated] Format markdown
  DEVELOPMENT.md
  README.md
Labels: approved, cla: yes, lgtm, size/S

#54 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: cla: yes, lgtm, size/XS

#53 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#55 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#56 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#57 Replace golint with revive
  .golangci.yaml
Labels: approved, cla: yes, lgtm, size/XS

#58 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#61 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#62 Fix revive related linting issues
  test/clients.go
  test/conformance/ingressv2/util.go
Labels: approved, cla: yes, lgtm, size/XS

#60 Remove CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS
