Repository knative-extensions/net-gateway-api, pull requests merged in 2021-04, with the labels that each got.

#24 [Automated] Format markdown
  CONTRIBUTING.md
  DEVELOPMENT.md
  README.md
Labels: approved, cla: yes, lgtm, size/S

#25 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#28 Add TestRewriteHost
  test/conformance/ingressv2/rewrite.go
  test/conformance/ingressv2/run.go
  test/conformance/ingressv2/util.go
Labels: approved, cla: yes, lgtm, size/L

#27 Add contour-operator for kind-e2e test
  .github/workflows/kind-e2e.yaml
  test/conformance/ingressv2/run.go
  third_party/contour-head/gateway/gateway-external.yaml
  third_party/contour-head/gateway/gateway-internal.yaml
  third_party/contour-head/install-operator.sh
  third_party/istio-head/gateway/300-gateway.yaml
  third_party/istio-head/gateway/300-gatewayclass.yaml
Labels: approved, cla: yes, lgtm, size/L

#31 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/domain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#32 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/rule.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#35 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#34 Append headers to TestRule to verify we hit expected backend
  test/conformance/ingressv2/rule.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/S

#38 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#33 Add IsHTTPRouteReady status check
  test/conformance/ingressv2/util.go
  test/conformance/ingressv2/util_test.go
Labels: approved, cla: yes, lgtm, size/L

#39 Add contour tests
  test/conformance/ingressv2/run.go
Labels: approved, cla: yes, lgtm, size/XS

#40 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#42 Add TestPercentage to contour
  test/conformance/ingressv2/run.go
Labels: approved, cla: yes, lgtm, size/XS

#41 Wait for contour-operator deployment instead of pod
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#44 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/serverlessservice_types.go
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#45 Copy OWNERS_ALIASES from knative/community; fill in OWNERS files
  OWNERS
  OWNERS_ALIASES
  hack/OWNERS
  test/OWNERS
Labels: approved, cla: yes, lgtm, size/L

#46 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#43 Add TestVisibility in Contour
  .github/workflows/kind-e2e.yaml
  test/conformance/ingressv2/run.go
  test/conformance/ingressv2/util.go
  test/conformance/ingressv2/visibility.go
  third_party/contour-head/gateway/gateway-internal.yaml
Labels: approved, cla: yes, lgtm, size/L
