Repository knative-extensions/net-gateway-api, pull requests merged in 2021-06, with the labels that each got.

#65 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/clients.go
  vendor/knative.dev/networking/test/util.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#64 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#66 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#68 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/errors.go
  vendor/github.com/evanphx/json-patch/v5/go.mod
  vendor/github.com/evanphx/json-patch/v5/go.sum
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/go.uber.org/zap/.travis.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/CONTRIBUTING.md
  vendor/go.uber.org/zap/FAQ.md
  vendor/go.uber.org/zap/Makefile
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/http_handler.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/error.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/write_syncer.go
  vendor/gopkg.in/evanphx/json-patch.v4/.travis.yml
  vendor/gopkg.in/evanphx/json-patch.v4/README.md
  vendor/knative.dev/pkg/apis/duck/patch.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#71 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: approved, cla: yes, lgtm, size/M

#72 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#73 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#76 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#77 Bump k8s version in kind-e2e.yaml to v1.19, 1.20 and 1.21
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/S

#80 Drop use of pkgtest.KubeClient
  go.mod
  go.sum
  test/clients.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/test/cleanup.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#70 Use common function to get port pointer
  DEVELOPMENT.md
  test/conformance/ingressv2/basic.go
  test/conformance/ingressv2/grpc.go
  test/conformance/ingressv2/headers.go
  test/conformance/ingressv2/hosts.go
  test/conformance/ingressv2/path.go
  test/conformance/ingressv2/percentage.go
  test/conformance/ingressv2/rewrite.go
  test/conformance/ingressv2/rule.go
  test/conformance/ingressv2/timeout.go
  test/conformance/ingressv2/util.go
  test/conformance/ingressv2/visibility.go
  test/conformance/ingressv2/websocket.go
Labels: approved, cla: yes, kind/cleanup, lgtm, size/L

#81 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#82 [main] Upgrade to latest dependencies
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
Labels: approved, cla: yes, lgtm, size/XS

#83 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#84 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#85 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/environment/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#86 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#87 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#90 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/XS

#88 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#89 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#91 drop e2e scheduled runs to once a day
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS
