Repository knative-extensions/net-gateway-api, pull requests merged in 2021-09, with the labels that each got.

#125 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: cla: yes, size/S, lgtm, approved

#126 drop scheduled actions these fill up the job queue causing delays
  .github/workflows/kind-e2e.yaml
Labels: cla: yes, size/XS, lgtm, approved

#127 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/leader.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M, approved

#129 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M, approved

#131 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/podspec_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_validation.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L, approved

#132 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/podspec_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_validation.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L, approved

#133 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/modules.txt
Labels: cla: yes, size/S, lgtm, approved

#134 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M, approved

#136 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/XS, lgtm, approved

#137 Drop K8s 1.19 as it's no longer supported
  .github/workflows/kind-e2e.yaml
Labels: cla: yes, size/S, lgtm, approved

#135 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/networking/test/conformance/ingress/httpoption.go
  vendor/knative.dev/networking/test/conformance/ingress/tls.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L, approved

#139 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, size/S, lgtm, approved

#138 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/S, lgtm, approved

#141 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/modules.txt
Labels: cla: yes, size/S, lgtm, approved

#142 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, size/S, lgtm, approved

#143 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/S, lgtm, approved

#112 Update contour configurations
  third_party/contour-head/gateway/gateway-external.yaml
  third_party/contour-head/gateway/gateway-internal.yaml
Labels: cla: yes, size/S, lgtm, approved

#145 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/cronjob_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/cronjob_types.go
  vendor/knative.dev/pkg/apis/duck/v1/cronjob_validation.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L, approved

#144 [main] Update community files
  CODE-OF-CONDUCT.md
Labels: cla: yes, lgtm, size/M, approved
