Repository knative-extensions/net-gateway-api, pull requests merged in 2021-11, with the labels that each got.

#167 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M, approved

#169 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, size/S, lgtm, approved

#170 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, lgtm, size/L, approved

#174 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/S, lgtm, approved

#175 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, size/XS, lgtm, approved

#176 Fix to parse `NamespacedName` in config-gateway
  pkg/reconciler/ingress/config/gateway.go
  pkg/reconciler/ingress/config/gateway_test.go
Labels: cla: yes, lgtm, size/M, approved

#177 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M, approved

#178 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M, approved

#182 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M, approved

#180 Use each IP to probe public and private services
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/lister.go
  pkg/reconciler/ingress/lister_test.go
  third_party/contour-head/gateway/gateway-internal.yaml
Labels: cla: yes, lgtm, size/L, approved

#183 Run controller e2e test with Contour
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
  config/203-local-gateway.yaml
  config/300-gateway-local.yaml
  config/300-gateway.yaml
  test/conformance/ingressv2/run.go
  test/conformance/ingressv2/util.go
  test/kind-conformance-contour.sh
  test/kind-conformance-istio.sh
  test/kind-e2e-contour.sh
  test/kind-e2e-istio.sh
  third_party/contour-head/gateway/config-gateway.yaml
  third_party/contour-head/gateway/gateway-external.yaml
  third_party/contour-head/gateway/gateway-internal.yaml
  third_party/istio-head/gateway/300-gateway-local.yaml
  third_party/istio-head/gateway/300-gateway.yaml
  third_party/istio-head/gateway/300-gatewayclass.yaml
Labels: cla: yes, size/XL, lgtm, approved

#181 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, lgtm, size/M, approved

#184 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/test/request.go
  vendor/modules.txt
Labels: cla: yes, size/S, lgtm, approved

#186 Drop t.Parallel() in TestVisibilitySplit until issues/185 was fixed
  test/conformance/ingressv2/visibility.go
  test/kind-conformance-contour.sh
  test/kind-conformance-istio.sh
Labels: cla: yes, size/XS, lgtm, approved

#187 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, size/S, lgtm, approved

#188 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M, approved

#190 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M, approved

#191 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/reconciler/filter.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L, approved

#189 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/XS, lgtm, approved

#192 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L, approved

#196 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/modules.txt
Labels: cla: yes, size/S, lgtm, approved

#200 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/kmap/lookup.go
  vendor/knative.dev/pkg/kmap/map.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L, approved

#201 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, size/S, lgtm, approved

#197 Add hack/release.sh
  config/controller.yaml
  hack/release.sh
Labels: cla: yes, lgtm, size/M, approved

#194 Add unit test for reconciler
  pkg/reconciler/ingress/ingress_test.go
Labels: cla: yes, lgtm, size/L, approved

#193 Add getting started in README
  README.md
Labels: cla: yes, lgtm, size/M, approved

#195 Add e2e test script
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
  test/e2e-common.sh
  test/e2e-tests.sh
  test/upload-test-images.sh
Labels: cla: yes, lgtm, size/L, approved

#202 Add HA test for net-gateway-api controller
  README.md
  test/e2e-common.sh
  test/e2e-tests.sh
  test/ha/controller_test.go
  test/ha/ha.go
  test/kind-e2e-contour.sh
  test/kind-e2e-istio.sh
  vendor/knative.dev/pkg/test/ha/ha.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/L, approved

#203 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M, approved

#204 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/modules.txt
Labels: cla: yes, size/S, lgtm, approved

#207 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: cla: yes, size/XS, lgtm, approved

#209 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: cla: yes, lgtm, size/M, approved

#210 Add istio-gateway.yaml and contour-gateway.yaml to release manifests
  DEVELOPMENT.md
  README.md
  hack/release.sh
  test/e2e-common.sh
  test/kind-conformance-contour.sh
  test/kind-conformance-istio.sh
  test/kind-e2e-contour.sh
  test/kind-e2e-istio.sh
  third_party/contour/gateway/config-gateway.yaml
  third_party/contour/gateway/gateway-external.yaml
  third_party/contour/gateway/gateway-internal.yaml
  third_party/contour/install-operator.sh
  third_party/istio/gateway/203-local-gateway.yaml
  third_party/istio/gateway/300-gateway-local.yaml
  third_party/istio/gateway/300-gateway.yaml
  third_party/istio/gateway/300-gatewayclass.yaml
  third_party/istio/install-istio.sh
  third_party/istio/istio-ci-no-mesh.yaml
  third_party/istio/istio-kind-no-mesh.yaml
Labels: cla: yes, lgtm, size/M, approved
