Repository knative-extensions/net-gateway-api, pull requests merged in 2022-04, with the labels that each got.

#269 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/CODE-OF-CONDUCT.md
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/modules.txt
Labels: lgtm, size/M, approved

#270 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, lgtm, approved

#272 drop legacy serving.knative.dev/release label
  config/200-clusterrole.yaml
  config/config-gateway.yaml
  config/controller.yaml
  hack/release.sh
  hack/update-codegen.sh
  hack/update-k8s-deps.sh
  pkg/reconciler/ingress/config/testdata/config-gateway.yaml
  pkg/reconciler/ingress/config/testdata/config-network.yaml
  test/config/201-clusterrole-core.yaml
  test/config/chaosduck.yaml
  test/config/leader-election.yaml
Labels: lgtm, size/M, approved

#276 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#277 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#278 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#279 drop serving release label
  test/config/200-service-account.yaml
  third_party/istio/gateway/203-local-gateway.yaml
Labels: size/S, lgtm, approved

#273 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, size/L, approved

#280 Bump k8s version in KinD
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
Labels: lgtm, size/M, approved

#274 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#282 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#281 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: lgtm, size/M, approved
