Repository knative-extensions/net-gateway-api, pull requests merged in 2022-07, with the labels that each got.

#324 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#325 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/networking/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/endpoints.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/endpoints/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/factory.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/fake/fake.go
  vendor/knative.dev/pkg/hack/generate-knative.sh
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#326 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#328 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#316 Add support for TLS (conformance test passes)
  config/200-clusterrole.yaml
  docs/test-version.md
  hack/test-env.sh
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/controller_test.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/reconcile_resources.go
  pkg/reconciler/ingress/resources/httproute.go
  pkg/reconciler/ingress/resources/httproute_test.go
  pkg/reconciler/ingress/resources/reference_grant.go
  pkg/reconciler/testing/listers.go
Labels: size/XL, lgtm, kind/enhancement, approved

#331 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/S, lgtm, approved

#329 Bump Contour to a recent commit
  docs/test-version.md
  hack/test-env.sh
Labels: size/XS, lgtm, approved

#330 Bump Istio to v1.14.1
  docs/test-version.md
  hack/test-env.sh
Labels: size/XS, lgtm, approved

#334 ⬆️ Bump Gatewy API version to v0.5.0
  config/100-gateway-api.yaml
  docs/test-version.md
  go.mod
  go.sum
  hack/test-env.sh
  vendor/modules.txt
  vendor/sigs.k8s.io/gateway-api/apis/v1alpha2/gateway_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1alpha2/httproute_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1alpha2/object_reference_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1alpha2/referencegrant_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1alpha2/shared_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1alpha2/tcproute_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1alpha2/tlsroute_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1beta1/httproute_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1beta1/shared_types.go
Labels: size/XL, lgtm, approved

#337 Bump Go version to 1.18 for CI
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#338 Bump go.mod to v1.18
  go.mod
  go.sum
Labels: lgtm, size/L, approved

#339 Stop using knative.dev/pkg/pool, use errgroup instead
  go.mod
  go.sum
  test/conformance/gateway-api/path.go
  test/conformance/gateway-api/percentage.go
  test/conformance/gateway-api/visibility.go
  vendor/golang.org/x/sync/AUTHORS
  vendor/golang.org/x/sync/CONTRIBUTORS
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/modules.txt
Labels: ok-to-test, lgtm, size/L, approved

#340 pull in latest knative.dev/hack changes
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#341 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
