Repository knative-extensions/net-gateway-api, pull requests merged in 2022-06, with the labels that each got.

#298 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#299 Update README.md
  README.md
Labels: size/XS, lgtm, approved

#300 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#301 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#302 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#304 Updates for deprecated network dependencies
  pkg/reconciler/ingress/config/store.go
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/controller_test.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/resources/httproute.go
  test/conformance/ingressv2/headers.go
Labels: lgtm, size/M, approved

#303 bump kind and k8s versions in kind-e2e tests
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
Labels: lgtm, size/M, approved

#305 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/gatewayapi/clientset/versioned/clientset.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/certificates/v1/types.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/client-go/kubernetes/clientset.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/generator_for_clientset.go
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/networking/pkg/deprecated_config.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#310 Fix probes for internal addresses when using one contour
  pkg/reconciler/ingress/lister.go
  pkg/reconciler/ingress/lister_test.go
  test/kind-e2e-istio.sh
Labels: lgtm, size/L, approved, kind/cleanup, kind/bug

#312 Skip Istio TestVisibilitySplit failing test for now
  docs/.test-version.template
  hack/test-env.sh
  test/e2e-tests.sh
  test/kind-conformance-contour.sh
  test/kind-conformance-istio.sh
  test/kind-e2e-contour.sh
  test/kind-e2e-istio.sh
Labels: size/S, lgtm, approved

#314 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, lgtm, approved, skip-review

#320 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#321 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/pkg/hack/generate-knative.sh
  vendor/modules.txt
Labels: size/XS, lgtm, approved
