Repository knative-extensions/net-gateway-api, pull requests merged in 2022-08, with the labels that each got.

#342 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/presubmit-tests.sh
  vendor/modules.txt
Labels: lgtm, size/M, approved

#343 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/internal/dbg/dbg.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#345 bump istio to v1.14.3
  docs/test-version.md
  hack/test-env.sh
Labels: size/XS, lgtm, approved

#344 bump contour to 1.22
  docs/test-version.md
  hack/test-env.sh
Labels: size/XS, lgtm, approved

#346 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#347 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#356 Add a checklist for tracking conformance tests succeed for each implementation
  .github/ISSUE_TEMPLATE/conformance-tests-checklist.yaml
Labels: lgtm, size/M, approved

#359 Improve conformance test checklist label/description
  .github/ISSUE_TEMPLATE/conformance-tests-checklist.yaml
Labels: size/XS, lgtm, approved

#372 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#373 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#374 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#375 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#377 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#376 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#378 Test KIngress conformance visibility with contour
  docs/test-version.md
  hack/test-env.sh
Labels: size/XS, lgtm, approved

#380 Add checklist for kingress conformance tests
  .github/ISSUE_TEMPLATE/kingress-tests-checklist.yaml
Labels: lgtm, size/M, approved

#381 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#382 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#385 Test KIngress conformance visibility/path with contour
  docs/test-version.md
  hack/test-env.sh
Labels: size/XS, lgtm, approved
