Repository knative-extensions/net-gateway-api, pull requests merged in 2022-11, with the labels that each got.

#404 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/modules.txt
Labels: lgtm, size/XXL, approved

#406 bump istio, contour and gateway api version
  config/100-gateway-api.yaml
  docs/test-version.md
  go.mod
  go.sum
  hack/test-env.sh
  hack/verify-codegen.sh
  pkg/client/gatewayapi/clientset/versioned/fake/register.go
  pkg/client/gatewayapi/clientset/versioned/scheme/register.go
  vendor/modules.txt
  vendor/sigs.k8s.io/gateway-api/apis/v1alpha2/httproute_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1alpha2/object_reference_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1alpha2/shared_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1beta1/httproute_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1beta1/object_reference_types.go
  vendor/sigs.k8s.io/gateway-api/apis/v1beta1/shared_types.go
  vendor/sigs.k8s.io/gateway-api/pkg/client/clientset/versioned/scheme/register.go
Labels: lgtm, size/L, approved

#408 Fix indentation so gofmt doesn't complain
  pkg/reconciler/ingress/resources/helpers.go
  test/conformance/gateway-api/util.go
Labels: size/S, lgtm, approved

#407 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#411 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#410 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/configmap/doc.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/hash/doc.go
  vendor/knative.dev/pkg/injection/doc.go
  vendor/knative.dev/pkg/injection/injection.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/reconciler/testing/hooks.go
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/knative.dev/pkg/reconciler/testing/sorter.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/zipkin/doc.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#412 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/networking/pkg/ingress/ingress.go
  vendor/knative.dev/networking/pkg/prober/prober.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/test_images/runtime/handlers/cgroup.go
  vendor/knative.dev/networking/test/test_images/runtime/handlers/file_access_attempt.go
  vendor/knative.dev/networking/test/test_images/wsserver/echo.go
  vendor/knative.dev/networking/test/util.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#413 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#415 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/M, approved

#416 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
  vendor/k8s.io/gengo/examples/set-gen/generators/sets.go
  vendor/k8s.io/gengo/examples/set-gen/sets/byte.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int64.go
  vendor/k8s.io/gengo/examples/set-gen/sets/string.go
  vendor/k8s.io/gengo/generator/import_tracker.go
  vendor/k8s.io/gengo/namer/import_tracker.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/utils/net/port.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#417 fix k8s deprecation
  pkg/reconciler/ingress/resources/httproute.go
  pkg/reconciler/ingress/resources/httproute_test.go
  test/conformance/gateway-api/grpc.go
  test/conformance/gateway-api/headers.go
  test/conformance/gateway-api/path.go
  test/conformance/gateway-api/rule.go
  test/conformance/gateway-api/visibility.go
  test/conformance/gateway-api/websocket.go
Labels: lgtm, size/M, approved

#414 Simplify e2e scripts & support contour
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
  README.md
  hack/release.sh
  test/config/chaosduck.yaml
  test/e2e-common.sh
  test/e2e-library-deployments.sh
  test/e2e-library.sh
  test/e2e-tests.sh
  test/kind-conformance-contour.sh
  test/kind-conformance-istio.sh
  test/kind-e2e-contour.sh
  test/kind-e2e-istio.sh
  test/presubmit-tests.sh
  third_party/contour/config-gateway.yaml
  third_party/contour/gateway-external.yaml
  third_party/contour/gateway-internal.yaml
  third_party/istio/203-local-gateway.yaml
  third_party/istio/300-gateway-local.yaml
  third_party/istio/300-gateway.yaml
  third_party/istio/300-gatewayclass.yaml
Labels: size/XL, lgtm, approved

#419 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#418 bump istio to 1.16.0
  docs/test-version.md
  hack/test-env.sh
Labels: size/XS, lgtm, approved

#420 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: lgtm, size/M, approved
