Repository knative-extensions/net-gateway-api, pull requests merged in 2022-10, with the labels that each got.

#396 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#395 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/pkg/webhook/helper.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#398 Bump k8s version in KinD
  .github/workflows/kind-conformance.yaml
  .github/workflows/kind-e2e.yaml
Labels: lgtm, size/M, approved

#401 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/grpc.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#403 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: lgtm, size/L, approved
