Repository knative-extensions/net-gateway-api, pull requests merged in 2023-02, with the labels that each got.

#441 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#442 Use serving-writers and reviewer teams
  OWNERS
Labels: size/XS, lgtm, approved

#443 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#444 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#445 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/L, approved

#447 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#448 Bump Istio version to 1.7.0
  docs/test-version.md
  hack/test-env.sh
Labels: size/XS, lgtm, approved

#449 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#451 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/reconciler.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#452 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/M, approved

#453 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#454 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/client/injection/reconciler/networking/v1alpha1/ingress/controller.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#459 [release-1.9] trigger to build release with go1.19.6
  go.mod
Labels: size/XS, lgtm, approved
