Repository knative-extensions/net-gateway-api, pull requests merged in 2023-10, with the labels that each got.

#552 Propagate HostRewrite from Knative Ingress to HttpRoute
  docs/test-version.md
  hack/test-env.sh
  pkg/reconciler/ingress/resources/httproute.go
  pkg/reconciler/ingress/resources/httproute_test.go
Labels: lgtm, size/M, kind/enhancement, approved

#554 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#556 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#555 Bump to contour 1.26 and use gateway-provisioner
  README.md
  docs/test-version.md
  hack/test-env.sh
  test/e2e-common.sh
  third_party/contour/config-gateway.yaml
  third_party/contour/gateway-external.yaml
  third_party/contour/gateway-internal.yaml
Labels: lgtm, size/L, kind/enhancement, approved

#560 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#567 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_portable.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#565 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#564 removed duplicated section from docs
  README.md
Labels: kind/documentation, size/XS, lgtm, approved

#569 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#568 Bump Istio to 1.19.3
  docs/test-version.md
  hack/test-env.sh
Labels: size/XS, lgtm, approved

#571 Add gateway api crds file to release
  hack/release.sh
Labels: size/XS, lgtm, approved, kind/cleanup

#573 Wait for deploy/gateway-api-admission-server to make sure webhook is ready
  test/e2e-common.sh
Labels: size/XS, lgtm, approved, kind/cleanup

#575 [release-1.10] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#574 [release-1.11] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#576 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: size/S, lgtm, approved
