Repository knative-extensions/net-gateway-api, pull requests merged in 2023-01, with the labels that each got.

#430 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/test/logstream/interface.go
  vendor/knative.dev/pkg/test/logstream/v2/stream.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#432 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#433 Update development documentation
  .github/workflows/kind-e2e.yaml
  .gitignore
  DEVELOPMENT.md
Labels: ok-to-test, kind/documentation, lgtm, size/M, approved, kind/cleanup

#434 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#435 Bump Gateway API testing version to v0.6.0
  .github/workflows/kind-e2e.yaml
  config/100-gateway-api.yaml
  docs/test-version.md
  hack/test-env.sh
Labels: lgtm, size/XXL, approved

#431 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#439 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#436 Use v1beta1 Gateway
  third_party/contour/gateway-external.yaml
  third_party/contour/gateway-internal.yaml
  third_party/istio/300-gateway.yaml
  third_party/istio/300-gatewayclass.yaml
Labels: size/S, lgtm, approved

#440 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved
