Repository knative-extensions/net-gateway-api, pull requests merged in 2023-09, with the labels that each got.

#524 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#525 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#526 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/embed.go
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, size/M, approved

#528 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#530 add seccompProfile to controller security context
  config/controller.yaml
Labels: size/XS, lgtm, approved

#532 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#534 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/config/config-network.yaml
  vendor/modules.txt
Labels: lgtm, size/M, approved

#540 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#544 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/google.golang.org/grpc/call.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#545 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#548 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, size/L, approved

#549 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/apis/duck/v1/auth_types.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#547 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#550 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/hack/embed.go
  vendor/modules.txt
Labels: lgtm, size/M, approved
