Repository knative-extensions/net-gateway-api, pull requests merged in 2023-05, with the labels that each got.

#479 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#483 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#485 Bump Kind Version
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#486 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, skip-review

#487 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: lgtm, size/M, approved
