Repository knative-extensions/net-gateway-api, pull requests merged in 2023-11, with the labels that each got.

#578 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/LICENSE
  third_party/VENDOR-LICENSE/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/NOTICE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/LICENSE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/NOTICE
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/.gitignore
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/Makefile
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/decode.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/doc.go
  vendor/github.com/matttproud/golang_protobuf_extensions/v2/pbutil/encode.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/google.golang.org/grpc/README.md
  vendor/google.golang.org/grpc/attributes/attributes.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/encoding/encoding.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/backoff/backoff.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/status/status.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/tap/tap.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: lgtm, size/L, approved

#579 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  pkg/client/injection/informers/factory/filtered/filtered_factory.go
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/CONTRIBUTING.md
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/gorilla/websocket/.editorconfig
  vendor/github.com/gorilla/websocket/.gitignore
  vendor/github.com/gorilla/websocket/.golangci.yml
  vendor/github.com/gorilla/websocket/AUTHORS
  vendor/github.com/gorilla/websocket/LICENSE
  vendor/github.com/gorilla/websocket/Makefile
  vendor/github.com/gorilla/websocket/README.md
  vendor/github.com/gorilla/websocket/client.go
  vendor/github.com/gorilla/websocket/compression.go
  vendor/github.com/gorilla/websocket/conn.go
  vendor/github.com/gorilla/websocket/mask.go
  vendor/github.com/gorilla/websocket/proxy.go
  vendor/github.com/gorilla/websocket/server.go
  vendor/github.com/gorilla/websocket/tls_handshake.go
  vendor/github.com/gorilla/websocket/tls_handshake_116.go
  vendor/github.com/gorilla/websocket/util.go
  vendor/github.com/gorilla/websocket/x_net_proxy.go
  vendor/golang.org/x/net/internal/socks/client.go
  vendor/golang.org/x/net/internal/socks/socks.go
  vendor/golang.org/x/net/proxy/dial.go
  vendor/golang.org/x/net/proxy/direct.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/proxy/proxy.go
  vendor/golang.org/x/net/proxy/socks5.go
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/modules.txt
Labels: lgtm, size/XXL, approved

#581 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#584 Make SECURITY.md consistent
  SECURITY.md
Labels: size/XS, lgtm, approved

#586 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#585 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_helpers.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#589 Drop testing on k8s v1.26
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#590 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
