Repository knative-extensions/net-gateway-api, pull requests merged in 2024-02, with the labels that each got.

#609 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#612 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#613 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#614 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#617 drop k8s 1.27 from kind testing and add v1.29
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved

#618 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/expfmt/text_create.go
  vendor/github.com/prometheus/common/model/labels.go
  vendor/github.com/prometheus/common/model/metric.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/golang.org/x/tools/internal/imports/zstdlib.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: lgtm, size/XXL, approved

#619 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_lifecycle.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#625 Bump Contour to v1.28.1
  docs/test-version.md
  hack/test-env.sh
Labels: size/XS, lgtm, approved

#626 bump golang to v1.22
  .github/workflows/kind-e2e.yaml
Labels: size/S, lgtm, approved

#628 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/networking/config/certificate.yaml
  vendor/knative.dev/networking/config/domain-claim.yaml
  vendor/knative.dev/networking/config/domain.yaml
  vendor/knative.dev/networking/config/ingress.yaml
  vendor/knative.dev/networking/config/realm.yaml
  vendor/knative.dev/networking/config/serverlessservice.yaml
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#627 bump istio to 1.20.3 and gateway api to v1
  docs/test-version.md
  hack/test-env.sh
  test/e2e-common.sh
  third_party/gateway-api/gateway-api.yaml
Labels: lgtm, size/XXL, approved

#630 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/knative.dev/networking/test/conformance/ingress/basic.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: lgtm, size/L, approved
