Repository knative-extensions/net-gateway-api, pull requests merged in 2024-03, with the labels that each got.

#634 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#636 disable update test for istio
  docs/test-version.md
  hack/test-env.sh
Labels: size/XS, lgtm, approved

#635 enable http2 tests for contour
  docs/test-version.md
  hack/test-env.sh
Labels: size/XS, lgtm, approved

#637 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/test/e2e-common.sh
  vendor/knative.dev/networking/test/e2e-tests.sh
  vendor/knative.dev/networking/test/presubmit-tests.sh
  vendor/modules.txt
Labels: lgtm, size/M, approved

#640 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/client_model/go/metrics.pb.go
  vendor/github.com/prometheus/common/expfmt/encode.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/github.com/prometheus/common/model/labelset.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#643 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#647 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/golang/protobuf/ptypes/any.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#644 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#649 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/expfmt.go
  vendor/github.com/prometheus/common/expfmt/openmetrics_create.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#650 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#651 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#652 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#653 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/http/header/header.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#654 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#655 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/SECURITY.md
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, size/M, approved

#656 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, size/M, approved

#659 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/modules.txt
Labels: size/S, lgtm, approved
