Repository knative-extensions/net-gateway-api, pull requests merged in 2024-04, with the labels that each got.

#658 add the port name used by contour in lister matching
  pkg/reconciler/ingress/lister.go
Labels: size/XS, lgtm, approved

#660 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/webhook/stats_reporter.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#662 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/reconciler/testing/context.go
  vendor/knative.dev/pkg/test/ha/ha.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#661 drop issue template
  .github/ISSUE_TEMPLATE/kingress-tests-checklist.yaml
Labels: lgtm, size/M, approved

#664 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#666 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#670 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#669 Bump contour to 1.28.2
  docs/test-version.md
  hack/test-env.sh
Labels: size/XS, lgtm, approved

#671 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/basic.go
  vendor/knative.dev/networking/test/conformance/ingress/class.go
  vendor/knative.dev/networking/test/conformance/ingress/grpc.go
  vendor/knative.dev/networking/test/conformance/ingress/headers.go
  vendor/knative.dev/networking/test/conformance/ingress/httpoption.go
  vendor/knative.dev/networking/test/conformance/ingress/path.go
  vendor/knative.dev/networking/test/conformance/ingress/percentage.go
  vendor/knative.dev/networking/test/conformance/ingress/retry.go
  vendor/knative.dev/networking/test/conformance/ingress/rule.go
  vendor/knative.dev/networking/test/conformance/ingress/timeout.go
  vendor/knative.dev/networking/test/conformance/ingress/tls.go
  vendor/knative.dev/networking/test/conformance/ingress/update.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/conformance/ingress/visibility.go
  vendor/knative.dev/networking/test/conformance/ingress/websocket.go
  vendor/knative.dev/networking/test/e2e_flags.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#674 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/headers.go
  vendor/knative.dev/networking/test/test_images/runtime/handlers/handler.go
  vendor/knative.dev/networking/test/test_images/runtime/main.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#675 bump contour and istio
  docs/test-version.md
  hack/test-env.sh
Labels: size/XS, lgtm, approved

#676 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/prober/prober.go
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/knative.dev/networking/test/ingress.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#677 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/retry.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#678 refactor some probing tests
  pkg/reconciler/ingress/ingress_test.go
Labels: lgtm, size/L, approved

#680 Skip TLS conformance tests for Contour
  docs/test-version.md
  hack/test-env.sh
Labels: size/XS, lgtm, approved

#679 Fork the knative/networking Status.Prober
  go.mod
  pkg/status/status.go
  pkg/status/status_test.go
Labels: lgtm, size/XXL, approved

#683 fix interface to match prober
  pkg/status/status.go
Labels: size/XS, lgtm, approved

#684 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/channelz/funcs.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/networking/test/conformance/ingress/update.go
  vendor/modules.txt
Labels: lgtm, size/M, approved

#686 [contour] Re-enable TLS testing
  docs/test-version.md
  hack/test-env.sh
  third_party/contour/gateway-external.yaml
Labels: size/S, lgtm, approved

#672 Three-Phase Endpoint Probing
  docs/test-version.md
  hack/test-env.sh
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/fixtures_test.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/lister.go
  pkg/reconciler/ingress/lister_test.go
  pkg/reconciler/ingress/reconcile_resources.go
  pkg/reconciler/ingress/resources/httproute.go
  pkg/reconciler/ingress/resources/httproute_test.go
  vendor/knative.dev/networking/pkg/status/status.go
  vendor/modules.txt
Labels: lgtm, size/XXL, approved

#688 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#689 simplify contour naming
  test/e2e-common.sh
  third_party/contour/config-gateway.yaml
  third_party/contour/gateway-external.yaml
  third_party/contour/gateway-internal.yaml
Labels: lgtm, size/M, approved

#673 Opinionated knative gateway conformance
  test/e2e-common.sh
  test/e2e-tests.sh
  test/gatewayapi/README.md
  test/gatewayapi/go.mod
  test/gatewayapi/go.sum
  test/gatewayapi/knative_test.go
  third_party/contour/gateway-external.yaml
  third_party/contour/gateway-internal.yaml
Labels: lgtm, size/L, approved

#692 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/test/conformance/ingress/util.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#693 Fix probing when KIngress has multiple visibilities (External/ClusterLocal)
  pkg/reconciler/ingress/fixtures_test.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/lister_test.go
  pkg/reconciler/ingress/reconcile_resources.go
Labels: lgtm, size/XXL, approved

#694 Status probing is now tied to the HTTPRoute
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/reconcile_resources.go
  pkg/reconciler/ingress/resources/httproute.go
  pkg/status/status.go
  pkg/status/status_test.go
Labels: lgtm, size/L, approved

#690 Replace gateway apis v1beta1 with v1 apis
  hack/update-codegen.sh
  pkg/client/injection/informers/apis/v1/gateway/fake/fake.go
  pkg/client/injection/informers/apis/v1/gateway/filtered/fake/fake.go
  pkg/client/injection/informers/apis/v1/gateway/filtered/gateway.go
  pkg/client/injection/informers/apis/v1/gateway/gateway.go
  pkg/client/injection/informers/apis/v1/gatewayclass/fake/fake.go
  pkg/client/injection/informers/apis/v1/gatewayclass/filtered/fake/fake.go
  pkg/client/injection/informers/apis/v1/gatewayclass/filtered/gatewayclass.go
  pkg/client/injection/informers/apis/v1/gatewayclass/gatewayclass.go
  pkg/client/injection/informers/apis/v1/httproute/fake/fake.go
  pkg/client/injection/informers/apis/v1/httproute/filtered/fake/fake.go
  pkg/client/injection/informers/apis/v1/httproute/filtered/httproute.go
  pkg/client/injection/informers/apis/v1/httproute/httproute.go
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/controller_test.go
  pkg/reconciler/ingress/fixtures_test.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/lister.go
  pkg/reconciler/ingress/reconcile_resources.go
  pkg/reconciler/ingress/resources/httproute.go
  pkg/reconciler/ingress/resources/httproute_test.go
  pkg/reconciler/testing/listers.go
Labels: lgtm, size/L, approved

#697 Don't probe all the cluster local hosts
  pkg/reconciler/ingress/reconcile_resources.go
  pkg/reconciler/ingress/resources/helpers.go
Labels: size/S, lgtm, approved

#698 Fix probing getting stuck forever
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/reconcile_resources.go
Labels: lgtm, size/M, approved

#696 Cancel probing when the ingress or pod is deleted
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/controller_test.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/fake/fake.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/pod/pod.go
  vendor/modules.txt
Labels: lgtm, size/L, approved

#701 change the config-gateway format
  config/config-gateway.yaml
  hack/verify-codegen.sh
  pkg/reconciler/ingress/config/gateway.go
  pkg/reconciler/ingress/config/gateway_test.go
  pkg/reconciler/ingress/config/store.go
  pkg/reconciler/ingress/config/testdata/config-gateway.yaml
  pkg/reconciler/ingress/config/testdata/config-network.yaml
  pkg/reconciler/ingress/config/zz_generated.deepcopy.go
  pkg/reconciler/ingress/controller.go
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/lister.go
  pkg/reconciler/ingress/reconcile_resources.go
  pkg/reconciler/ingress/resources/httproute.go
  pkg/reconciler/ingress/resources/httproute_test.go
  test/e2e/gateway_config_test.go
  test/e2e/testdata/contour-no-service-vis.yaml
  test/e2e/testdata/istio-no-service-vis.yaml
  third_party/contour/config-gateway.yaml
Labels: size/XL, lgtm, approved

#706 replace v1beta1 apis with v1 in yaml files
  test/clients.go
  third_party/contour/gateway-external.yaml
  third_party/contour/gateway-internal.yaml
  third_party/istio/300-gateway-local.yaml
  third_party/istio/300-gateway.yaml
Labels: size/S, lgtm, approved

#699 [contour] add envoy resource request and limits
  third_party/contour/gateway-external.yaml
  third_party/contour/gateway-internal.yaml
Labels: size/S, lgtm, approved

#712 Promote Maturity Status to Beta
  README.md
Labels: size/XS, lgtm, approved

#710 allow the config-gateway to accepted supported features
  config/config-gateway.yaml
  hack/update-codegen.sh
  pkg/reconciler/ingress/config/doc.go
  pkg/reconciler/ingress/config/gateway.go
  pkg/reconciler/ingress/config/gateway_test.go
  pkg/reconciler/ingress/config/zz_generated.deepcopy.go
  pkg/reconciler/ingress/resources/httproute.go
  pkg/reconciler/ingress/resources/httproute_test.go
  test/e2e/testdata/contour-no-service-vis.yaml
  test/e2e/testdata/istio-no-service-vis.yaml
  third_party/contour/config-gateway.yaml
  third_party/contour/config_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/gateway-api/pkg/features/features.go
Labels: size/XL, lgtm, approved

#703 followup changes from #685
  pkg/reconciler/ingress/ingress.go
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/lister.go
  pkg/reconciler/ingress/lister_test.go
  test/e2e-common.sh
  test/e2e/gateway_config_test.go
Labels: lgtm, size/L, approved, kind/cleanup

#713 only run gateway conformance tests during nightly builds
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved

#718 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#719 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
