Repository knative-extensions/net-gateway-api, pull requests merged in 2024-12, with the labels that each got.

#790 Bump Kind and k8s version
  .github/workflows/kind-e2e.yaml
  docs/.test-version.template
  docs/test-version.md
  hack/test-env.sh
  test/e2e-tests.sh
  third_party/gateway-api/gateway-api.yaml
Labels: lgtm, size/XXL, approved

#788 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/tools/go/ast/astutil/imports.go
  vendor/golang.org/x/tools/go/gcexportdata/gcexportdata.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/go/types/objectpath/objectpath.go
  vendor/golang.org/x/tools/internal/gcimporter/iexport.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport_go122.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/source.go
  vendor/golang.org/x/tools/internal/imports/source_env.go
  vendor/golang.org/x/tools/internal/typeparams/free.go
  vendor/golang.org/x/tools/internal/typesinternal/types.go
  vendor/golang.org/x/tools/internal/versions/types.go
  vendor/google.golang.org/protobuf/encoding/protojson/well_known_types.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/editionssupport/editions.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: lgtm, size/XXL, approved

#792 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#793 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved
