Repository knative-extensions/net-gateway-api, pull requests merged in 2024-08, with the labels that each got.

#760 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sync/LICENSE
  vendor/modules.txt
Labels: size/S, lgtm, approved

#761 Use shared go set-up action
  .github/workflows/knative-dependabot.yaml
Labels: size/XS, lgtm, approved

#762 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#764 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved
