Repository knative-extensions/net-gateway-api, pull requests merged in 2025-03, with the labels that each got.

#829 Create a per ingress ReferenceGrant to avoid conflicts in the same namespace
  pkg/reconciler/ingress/ingress_test.go
  pkg/reconciler/ingress/resources/reference_grant.go
  pkg/reconciler/ingress/resources/reference_grant_test.go
Labels: ok-to-test, lgtm, size/L, approved

#828 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/internal/httpcommon/headermap.go
  vendor/golang.org/x/net/internal/httpcommon/request.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/tools/go/ast/astutil/rewrite.go
  vendor/golang.org/x/tools/go/ast/astutil/util.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/go/types/typeutil/map.go
  vendor/golang.org/x/tools/internal/event/keys/keys.go
  vendor/golang.org/x/tools/internal/event/label/label.go
  vendor/golang.org/x/tools/internal/gcimporter/bimport.go
  vendor/golang.org/x/tools/internal/gcimporter/iexport.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/internal/gcimporter/ureader_yes.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/packagesinternal/packages.go
  vendor/golang.org/x/tools/internal/stdlib/deps.go
  vendor/golang.org/x/tools/internal/stdlib/import.go
  vendor/golang.org/x/tools/internal/stdlib/manifest.go
  vendor/golang.org/x/tools/internal/stdlib/stdlib.go
  vendor/golang.org/x/tools/internal/typeparams/normalize.go
  vendor/golang.org/x/tools/internal/typesinternal/types.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/balancer/endpointsharding/endpointsharding.go
  vendor/google.golang.org/grpc/balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
  vendor/google.golang.org/grpc/balancer/roundrobin/roundrobin.go
  vendor/google.golang.org/grpc/balancer/subconn.go
  vendor/google.golang.org/grpc/balancer_wrapper.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/internal/balancer/gracefulswitch/gracefulswitch.go
  vendor/google.golang.org/grpc/internal/envconfig/xds.go
  vendor/google.golang.org/grpc/internal/grpcsync/oncefunc.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/proxyattributes/proxyattributes.go
  vendor/google.golang.org/grpc/internal/resolver/delegatingresolver/delegatingresolver.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/proxy.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/hack/boilerplate.go.txt
  vendor/knative.dev/hack/codegen-library.sh
  vendor/modules.txt
Labels: lgtm, size/XXL, approved

#825 [release-1.16] Upgrade to latest dependencies [skip-dot-release]
  go.mod
  go.sum
  test/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, size/M, approved

#832 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
