Repository knative-extensions/net-gateway-api, pull requests merged in 2025-02, with the labels that each got.

#811 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/github.com/spf13/pflag/.editorconfig
  vendor/github.com/spf13/pflag/.golangci.yaml
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/ip.go
  vendor/github.com/spf13/pflag/ipnet_slice.go
  vendor/github.com/spf13/pflag/string_array.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/certificate.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/clusterdomainclaim.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_certificate.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_clusterdomainclaim.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_ingress.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/fake/fake_serverlessservice.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/ingress.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/typed/networking/v1alpha1/serverlessservice.go
  vendor/knative.dev/networking/pkg/client/informers/externalversions/factory.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/certificate.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/clusterdomainclaim.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/ingress.go
  vendor/knative.dev/networking/pkg/client/listers/networking/v1alpha1/serverlessservice.go
  vendor/modules.txt
Labels: lgtm, size/XXL, approved

#819 Bump k8s and Kind version
  .github/workflows/kind-e2e.yaml
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved

#820 fix linter config
  .golangci.yaml
Labels: size/XS, lgtm, approved

#821 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
