Repository knative-extensions/net-gateway-api, pull requests merged in 2025-04, with the labels that each got.

#833 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#835 bump to golangci yaml v2
  .golangci.yaml
Labels: size/XS, lgtm, approved

#836 bump to golangci yaml v2
  .golangci.yaml
Labels: lgtm, size/L, approved

#838 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#839 bump ingress versions to latest
  docs/test-version.md
  hack/test-env.sh
  test/e2e-common.sh
Labels: size/S, lgtm, approved

#841 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
